server:
  port: 8088
  servlet:
    context-path: /gateway

zuul:
  sensitive-headers: Cookie

jwt:
  config:
    login-url: /auth/login
    type: signed

ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000
  
management:
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      show-details: always
