server:
  port: 8084

spring:
  application:
    name: notifier
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        jdbc:
          time_zone: UTC
  jmx:
    enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/microservices?serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: root
jwt:
  config:
    type: signed
    
management:
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      show-details: always

